### ISSUE TITLE
Converting Kafka Connect data to byte[] failed due to serialization error

### ISSUE THREAD

**Issue by olivernaaris** [awslabs/aws-glue-schema-registry#238]
Hi

I'm trying to get the AWS Glue Schema Registry to work on our infra and I'm getting the following error (added as a file).

[log_file.log](https://github.com/awslabs/aws-glue-schema-registry/files/10277005/log_file.log)

We are using the following config with Strimzi:
```
---
apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "payout-transactions-s3-1"
  labels:
    strimzi.io/cluster: debezium-kafka
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    connector.class: "io.debezium.connector.mysql.MySqlConnector"
    database.allowPublicKeyRetrieval: "true"
    database.server.id: "45871235678"
    database.hostname: "{{ .Values.debezium.hostname }}"
    database.port: "3306"
    database.user: "${file:/opt/kafka/external-configuration/connector-config/UsernamePassword:mysql_username}"
    database.password: "${file:/opt/kafka/external-configuration/connector-config/UsernamePassword:mysql_password}"
    database.history.kafka.bootstrap.servers: "{{ .Values.debezium.bootstrap_servers }}:9092"
    database.history.kafka.topic: "schema_changes.payout_service_s3"
    database.server.name: "payout_db_server_s3"
    database.history.skip.unparseable.ddl: true
    database.include.list: "payout_service"
    table.include.list: "payout_service.payout_transaction"
    topic.creation.groups: "payout_transaction"
    database.whitelist: "payout_service"
    topic.creation.default.replication.factor: 1
    topic.creation.default.partitions: 1
    topic.creation.default.cleanup.policy: "delete"
    topic.creation.default.delete.retention.ms: 86400000
    topic.creation.default.retention.ms: 604800000
    topic.creation.payout_transaction.include: "payout_db_server_s3.payout_service.payout_transaction"
    topic.creation.payout_transaction.partitions: 3
    topic.creation.payout_transaction.cleanup.policy: "delete"
    topic.creation.payout_transaction.delete.retention.ms: 86400000
    topic.creation.payout_transaction.retention.ms: 604800000
    connect.timeout.ms: "120000"
    decimal.handling.mode: "string"
    snapshot.mode: "initial"
    snapshot.locking.mode: "none"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: false
    internal.key.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    internal.key.converter.schemas.enable: false
    internal.value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    internal.value.converter.schemas.enable: false
    value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    value.converter.schemas.enable: true
    key.converter.region: "eu-central-1"
    value.converter.region: "eu-central-1"
    key.converter.schemaAutoRegistrationEnabled: true
    value.converter.schemaAutoRegistrationEnabled: true
    key.converter.avroRecordType: GENERIC_RECORD
    value.converter.avroRecordType: GENERIC_RECORD
    key.converter.schemaName: payout-transactions
    value.converter.schemaName: payout-transactions
    key.converter.registry.name: "glue-schema-registry"
    value.converter.registry.name: "glue-schema-registry"
---
apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "payout-connector-s3"
  labels:
    strimzi.io/cluster: debezium-kafka
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    name: "payout-connector-s3"
    connector.class: "io.confluent.connect.s3.S3SinkConnector"
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    topics: "payout_db_server_s3_1.payout_service.payout_transaction"
    format.class: "io.confluent.connect.s3.format.avro.AvroFormat"
    flush.size: "10000"
    s3.bucket.name: "transactions"
    s3.region: "eu-central-1"

```

**Comment by blacktooth** [comment]
From the logs you provided, it seems like the schema registry failed. This can happen if the new schema version being registered is not compatible with existing set of schemas. You can delete the schema using CLI / console, fix the schema definition to make it compatible with existing versions and retry above.

**Comment by pc-akothapeta** [comment]
I see few issues here. In the Mysql source connector key looks like is string. So you dont need to specify any of they other key.* properties. 
In your s3 sink connector you also need to specify key and value convertors same as in your source connector. Otherwise sink connector doesn't know how deserialize the value which is in avro
Try these

```
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: false
    internal.value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    internal.value.converter.schemas.enable: false
    value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    value.converter.schemas.enable: true
    value.converter.region: "eu-central-1"
    value.converter.schemaAutoRegistrationEnabled: true
    value.converter.avroRecordType: GENERIC_RECORD
    value.converter.schemaName: payout-transactions
    value.converter.registry.name: "glue-schema-registry"
```

**Comment by olivernaaris** [comment]
Hi and thanks for the help.
I ended up with the following config, which seems to somewhat work as I don't see the previous error anymore.

However, now one of the s3 sinks is working and the other one is giving error: `Caused by: software.amazon.awssdk.services.glue.model.EntityNotFoundException: Schema version is not found. SchemaVersionId: deb7e5c2-fe1c-4de0-9cac-b0315336a207`
```
---
apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "payout-transactions-mysql-source5"
  labels:
    strimzi.io/cluster: debezium-kafka
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    connector.class: "io.debezium.connector.mysql.MySqlConnector"
    database.allowPublicKeyRetrieval: "true"
    database.server.id: "45871235678"
    database.hostname: "{{ .Values.debezium.hostname }}"
    database.port: "3306"
    database.user: "${file:/opt/kafka/external-configuration/connector-config/UsernamePassword:mysql_username}"
    database.password: "${file:/opt/kafka/external-configuration/connector-config/UsernamePassword:mysql_password}"
    database.history.kafka.bootstrap.servers: "{{ .Values.debezium.bootstrap_servers }}:9092"
    database.history.kafka.topic: "schema_changes.payout_service_s3"
    database.server.name: "payout_db_server_s3"
    database.history.skip.unparseable.ddl: true
    database.include.list: "payout_service"
    table.include.list: "payout_service.payout_transaction"
    topic.creation.groups: "payout_transaction"
    database.whitelist: "payout_service"
    topic.creation.default.replication.factor: 1
    topic.creation.default.partitions: 3
    topic.creation.default.cleanup.policy: "delete"
    topic.creation.default.delete.retention.ms: 86400000
    topic.creation.default.retention.ms: 604800000
    topic.creation.payout_transaction.include: "payout_db_server_s3.payout_service.payout_transaction"
    topic.creation.payout_transaction.partitions: 3
    topic.creation.payout_transaction.cleanup.policy: "delete"
    topic.creation.payout_transaction.delete.retention.ms: 86400000
    topic.creation.payout_transaction.retention.ms: 604800000
    connect.timeout.ms: "120000"
    decimal.handling.mode: "string"
    snapshot.mode: "initial"
    snapshot.locking.mode: "none"
    key.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    key.converter.schemas.enable: false
    value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    value.converter.schemas.enable: true
    key.converter.region: "eu-central-1"
    value.converter.region: "eu-central-1"
    key.converter.schemaAutoRegistrationEnabled: true
    value.converter.schemaAutoRegistrationEnabled: true
    key.converter.avroRecordType: "GENERIC_RECORD"
    value.converter.avroRecordType: "GENERIC_RECORD"
    key.converter.registry.name: "{{ .Values.environment }}-glue-schema-registry"
    value.converter.registry.name: "{{ .Values.environment }}-glue-schema-registry"
    key.converter.schemaName: "payout_transaction_KeySchema"
    value.converter.schemaName: "payout_transaction_ValueSchema"
    schema.name.adjustment.mode: "none"
---
apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "payout-transactions-s3-sink2"
  labels:
    strimzi.io/cluster: debezium-kafka
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 10
  config:
    name: "payout-transactions-s3-sink2"
    connector.class: "io.confluent.connect.s3.S3SinkConnector"
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    topics: "payout_db_server_s3.payout_service.payout_transaction"
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: true
    flush.size: "10"
    s3.bucket.name: "{{ .Values.environment }}-transactions"
    s3.region: "eu-central-1"
    partitioner.class: "io.confluent.connect.storage.partitioner.HourlyPartitioner"
    path.format: "YYYY/MM/dd/HH"
    timezone: "UTC"
    locale: "en"
    key.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    key.converter.schemas.enable: false
    value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    value.converter.schemas.enable: true
    key.converter.region: "eu-central-1"
    value.converter.region: "eu-central-1"
    key.converter.schemaAutoRegistrationEnabled: true
    value.converter.schemaAutoRegistrationEnabled: true
    key.converter.avroRecordType: "GENERIC_RECORD"
    value.converter.avroRecordType: "GENERIC_RECORD"
    key.converter.registry.name: "{{ .Values.environment }}-glue-schema-registry"
    value.converter.registry.name: "{{ .Values.environment }}-glue-schema-registry"
    key.converter.schemaName: "payout_transaction_KeySchema"
    value.converter.schemaName: "payout_transaction_ValueSchema"
    schema.compatibility: "NONE"

```

**Comment by pc-akothapeta** [comment]
Hello @olivernaaris , this new error indicates that your connector container doesn't have access to Glue schema registry. Please make sure the AWS role/credentials you are using has access glue schema registry actions, e.g. like below

```
          - Effect: Allow
            Action:
              - glue:*Registr*
              - glue:*Schema*
            Resource: "*"

```

**Comment by olivernaaris** [comment]
> Hello @olivernaaris , this new error indicates that your connector container doesn't have access to Glue schema registry. Please make sure the AWS role/credentials you are using has access glue schema registry actions, e.g. like below
> 
> ```
>           - Effect: Allow
>             Action:
>               - glue:*Registr*
>               - glue:*Schema*
>             Resource: "*"
> ```

Both connectors (deposit and payout) are using the same iam role with the same policy. One connector was able to start correctly and access AWS Glue and the other did not. 
Honestly to me it seems that the iam role is not the issue, as I even tried to give more permissions which did not fix the issue. 
Is it possible that the sink connector has some internal state of the schema version that is stored in a Kafka topic?

**Comment by pc-akothapeta** [comment]
If you are using Key.converter as avro then you have to enable the schemas in Glue in both connectors. 
If you are using string converter then you dont have to specify any of the schema parameters for glue.
```
key.converter.schemas.enable: true
```

**Comment by olivernaaris** [comment]
This is the current config that I have. 
```
---
apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "deposit-transactions-mysql-source5"
  labels:
    strimzi.io/cluster: debezium-kafka
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    connector.class: "io.debezium.connector.mysql.MySqlConnector"
    database.allowPublicKeyRetrieval: "true"
    database.server.id: "84561278048"
    database.hostname: "{{ .Values.debezium.hostname }}"
    database.port: "3306"
    database.user: "${file:/opt/kafka/external-configuration/connector-config/UsernamePassword:mysql_username}"
    database.password: "${file:/opt/kafka/external-configuration/connector-config/UsernamePassword:mysql_password}"
    database.history.kafka.bootstrap.servers: "{{ .Values.debezium.bootstrap_servers }}:9092"
    database.history.kafka.topic: "schema_changes.deposit_service_s3"
    database.server.name: "deposit_db_server_s3"
    database.history.skip.unparseable.ddl: true
    database.include.list: "deposit_service"
    table.include.list: "deposit_service.deposit_transaction"
    topic.creation.groups: "deposit_transaction"
    database.whitelist: "deposit_service"
    topic.creation.default.replication.factor: 1
    topic.creation.default.partitions: 3
    topic.creation.default.cleanup.policy: "delete"
    topic.creation.default.delete.retention.ms: 86400000
    topic.creation.default.retention.ms: 604800000
    topic.creation.deposit_transaction_s3.include: "deposit_db_server_s3.deposit_service.deposit_transaction"
    topic.creation.deposit_transaction_s3.partitions: 3
    topic.creation.deposit_transaction_s3.cleanup.policy: "delete"
    topic.creation.deposit_transaction_s3.delete.retention.ms: 86400000
    topic.creation.deposit_transaction_s3.retention.ms: 604800000
    connect.timeout.ms: "120000"
    decimal.handling.mode: "string"
    snapshot.mode: "initial"
    snapshot.locking.mode: "none"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: false
    internal.value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    internal.value.converter.schemas.enable: false
    value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    value.converter.schemas.enable: true
    value.converter.region: "eu-central-1"
    value.converter.schemaAutoRegistrationEnabled: true
    value.converter.avroRecordType: "GENERIC_RECORD"
    value.converter.schemaName: "deposit-transactions"
    value.converter.registry.name: "{{ .Values.environment }}-glue-schema-registry"
    schema.compatibility: "NONE"
---
apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "deposit-transactions-s3-sink3"
  labels:
    strimzi.io/cluster: debezium-kafka
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 10
  config:
    name: "deposit-transactions-s3-sink3"
    connector.class: "io.confluent.connect.s3.S3SinkConnector"
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    topics: "deposit_db_server_s3.deposit_service.deposit_transaction"
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    flush.size: "10"
    s3.bucket.name: "{{ .Values.environment }}-transactions"
    s3.region: "eu-central-1"
    partitioner.class: "io.confluent.connect.storage.partitioner.HourlyPartitioner"
    path.format: "YYYY/MM/dd/HH"
    timezone: "UTC"
    locale: "en"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: false
    internal.value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    internal.value.converter.schemas.enable: false
    value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    value.converter.schemas.enable: true
    value.converter.region: "eu-central-1"
    value.converter.schemaAutoRegistrationEnabled: true
    value.converter.avroRecordType: "GENERIC_RECORD"
    value.converter.schemaName: "deposit-transactions"
    value.converter.registry.name: "{{ .Values.environment }}-glue-schema-registry"
    schema.compatibility: "NONE"

```

The payout-transactions connector has the same config as deposit-transactions connector and payout is working. For payout I can see the schema in Glue and files are pushed to S3. For deposit-service I get the following error.

```
Caused by: org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error:
  at com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter.toConnectData(AWSKafkaAvroConverter.java:118)
  at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
  at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:540)
  at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:496)
  at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
  at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
  ... 13 more
Caused by: com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException: com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException: Failed to get schema version Id = 59e24199-402c-4b1f-8812-f5d9c3be4bb3
  at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryDeserializationFacade.retrieveSchemaRegistrySchema(GlueSchemaRegistryDeserializationFacade.java:219)
  at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryDeserializationFacade.getAwsDeserializerSchema(GlueSchemaRegistryDeserializationFacade.java:201)
  at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryDeserializationFacade.deserialize(GlueSchemaRegistryDeserializationFacade.java:167)
  at com.amazonaws.services.schemaregistry.deserializers.avro.AWSKafkaAvroDeserializer.deserializeByHeaderVersionByte(AWSKafkaAvroDeserializer.java:149)
  at com.amazonaws.services.schemaregistry.deserializers.avro.AWSKafkaAvroDeserializer.deserialize(AWSKafkaAvroDeserializer.java:114)
  at com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter.toConnectData(AWSKafkaAvroConverter.java:116)
  ... 18 more
Caused by: com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException: Failed to get schema version Id = 59e24199-402c-4b1f-8812-f5d9c3be4bb3
  at com.amazonaws.services.schemaregistry.common.AWSSchemaRegistryClient.getSchemaVersionResponse(AWSSchemaRegistryClient.java:170)
  at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryDeserializationFacade$GlueSchemaRegistryDeserializationCacheLoader.load(GlueSchemaRegistryDeserializationFacade.java:257)
  at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryDeserializationFacade$GlueSchemaRegistryDeserializationCacheLoader.load(GlueSchemaRegistryDeserializationFacade.java:253)
  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
  at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
  at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryDeserializationFacade.retrieveSchemaRegistrySchema(GlueSchemaRegistryDeserializationFacade.java:217)

```

It makes no sense that both connector has identical config (they have different names and topics) and one works and the other does not...

**Comment by pc-akothapeta** [comment]
It should work. We are doing exactly same thing using AWS MSK, extracting data from Oracle and sinking them to S3 and it works fine. 
Couple of thing I can suggest is that

- Mysql source connector will use the Primary/unique keys as the kafka key. Make sure column is String, because you are specifying key converter as String. If not change it accordingly.
- Try removing the following from both connectors. 

```
    internal.value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    internal.value.converter.schemas.enable: false
    schema.compatibility: "NONE"
```

**Comment by olivernaaris** [comment]
> It should work. We are doing exactly same thing using AWS MSK, extracting data from Oracle and sinking them to S3 and it works fine. Couple of thing I can suggest is that
> 
> * Mysql source connector will use the Primary/unique keys as the kafka key. Make sure column is String, because you are specifying key converter as String. If not change it accordingly.
> * Try removing the following from both connectors.
> 
> ```
>     internal.value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
>     internal.value.converter.schemas.enable: false
>     schema.compatibility: "NONE"
> ```

Interestingly enough, both connectors started working after I removed those config lines. Then for testing, I deleted the AWS Glue schemas from AWS and restarted the connectors. After some minutes and after a few connectors restarts, the connectors re-created the schemas in AWS. 
But for some reason, the sink connectors are now failing again with the error: `Schema version is not found. SchemaVersionId: 70a31d0d-0cc6-4d5e-b66c-4e1f5efe41d9`. That schema version does not exist in AWS, but I'd expect that the connector should be able to fetch the new schema id from AWS.

**Comment by olivernaaris** [comment]
In the end I managed to get it working with the following config:

```
---
apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "analytics-deposit-transactions-mysql-source1"
  labels:
    strimzi.io/cluster: debezium-kafka
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    connector.class: "io.debezium.connector.mysql.MySqlConnector"
    database.allowPublicKeyRetrieval: "true"
    database.server.id: "84561278048"
    database.hostname: "{{ .Values.debezium.hostname }}"
    database.port: "3306"
    database.user: "${file:/opt/kafka/external-configuration/connector-config/UsernamePassword:mysql_username}"
    database.password: "${file:/opt/kafka/external-configuration/connector-config/UsernamePassword:mysql_password}"
    database.history.kafka.bootstrap.servers: "{{ .Values.debezium.bootstrap_servers }}:9092"
    database.history.kafka.topic: "schema_changes.deposit_service_s3"
    database.server.name: "deposit_db_server_s3"
    database.history.skip.unparseable.ddl: true
    database.include.list: "deposit_service"
    table.include.list: "deposit_service.deposit_transaction"
    topic.creation.groups: "deposit_transaction"
    database.whitelist: "deposit_service"
    topic.creation.default.replication.factor: 1
    topic.creation.default.partitions: 3
    topic.creation.default.cleanup.policy: "delete"
    topic.creation.default.delete.retention.ms: 86400000
    topic.creation.default.retention.ms: 604800000
    topic.creation.deposit_transaction_s3.include: "deposit_db_server_s3.deposit_service.deposit_transaction"
    topic.creation.deposit_transaction_s3.partitions: 3
    topic.creation.deposit_transaction_s3.cleanup.policy: "delete"
    topic.creation.deposit_transaction_s3.delete.retention.ms: 86400000
    topic.creation.deposit_transaction_s3.retention.ms: 604800000
    connect.timeout.ms: "120000"
    decimal.handling.mode: "string"
    snapshot.mode: "initial"
    snapshot.locking.mode: "none"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: false
    value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    value.converter.schemas.enable: true
    value.converter.region: "eu-central-1"
    value.converter.schemaAutoRegistrationEnabled: true
    value.converter.avroRecordType: "GENERIC_RECORD"
    value.converter.schemaName: "analytics-deposit-transactions"
    value.converter.registry.name: "{{ .Values.environment }}-glue-schema-registry"
---
apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "analytics-deposit-transactions-s3-sink1"
  labels:
    strimzi.io/cluster: debezium-kafka
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 10
  config:
    name: "analytics-deposit-transactions-s3-sink1"
    connector.class: "io.confluent.connect.s3.S3SinkConnector"
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    topics: "deposit_db_server_s3.deposit_service.deposit_transaction"
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    flush.size: "100"
    s3.bucket.name: "{{ .Values.environment }}-transactions"
    s3.region: "eu-central-1"
    partitioner.class: "io.confluent.connect.storage.partitioner.HourlyPartitioner"
    path.format: "YYYY/MM/dd/HH"
    timezone: "UTC"
    locale: "en"
    transforms: unwrap,insertOffset
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: true
    transforms.unwrap.delete.handling.mode: rewrite
    transforms.unwrap.add.fields: op
    transforms.insertOffset.type: org.apache.kafka.connect.transforms.InsertField$Value
    transforms.insertOffset.offset.field: __offset
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: false
    value.converter: "com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter"
    value.converter.schemas.enable: true
    value.converter.region: "eu-central-1"
    value.converter.schemaAutoRegistrationEnabled: true
    value.converter.avroRecordType: "GENERIC_RECORD"
    value.converter.schemaName: "analytics-deposit-transactions"
    value.converter.registry.name: "{{ .Values.environment }}-glue-schema-registry"

```

Thanks for the help.
