### ISSUE TITLE
Test `GlueSchemaRegistryConfigurationTest.testBuildConfig_noRegionConfigsSupplied_throwsException` fails in some build scenarios but not others

### ISSUE THREAD

**Issue by rmsutilidata** [awslabs/aws-glue-schema-registry#343]
In my local build environment I use `asdf` CLI tool to set up Java and Maven 3.9.6 as follows:
```
asdf plugin add java
asdf plugin add maven
asdf install java adoptopenjdk-8.0.402+6
asdf install maven latest
asdf local java adoptopenjdk-8.0.402+6
asdf local maven latest
```

Then I follow the instructions [here](https://github.com/awslabs/aws-glue-schema-registry/tree/master?tab=readme-ov-file#using-kafka-connect-with-aws-glue-schema-registry) exactly to successfully build.

We're trying to automate this build via Github Actions using the [setup-java](https://github.com/actions/setup-java) action to set up our Java environment. Since setup-java only supports certain [distributions](https://github.com/actions/setup-java) we decided to use Temurin distribution with version 8.0.402+6 to build our environment. setup-java automatically uses Maven 3.8.8.
```
      - name: Clone aws-glue-schema-registry repo
        uses: actions/checkout@v4
        with:
          repository: 'awslabs/aws-glue-schema-registry'
          ref: ${{ (inputs.aws-glue-schema-registry-tag == 'latest') && 'master' || inputs.aws-glue-schema-registry-tag }}
          path: ${{ github.workspace }}/share/aws-glue-schema-registry/

      - name: Set up JDK 8.0.402+6
        uses: actions/setup-java@v4
        with:
          java-version: '8.0.402+6'
          distribution: 'temurin'

      - name: Build aws-glue-schema-registry tools
        working-directory: ${{ github.workspace }}/share/aws-glue-schema-registry/build-tools/
        # A known error pops up that we can ignore: https://github.com/awslabs/aws-glue-schema-registry/issues/267
        continue-on-error: true
        run: |
          mvn clean install

      # Run in separate step because of known, ignorable error above
      - name: Build aws-glue-schema-registry jars
        working-directory: ${{ github.workspace }}/share/aws-glue-schema-registry/
        run: |
          mvn clean install
          mvn dependency:copy-dependencies
```

The last step gives us this failed test:
```
Error:  Failures: 
Error:    GlueSchemaRegistryConfigurationTest.testBuildConfig_noRegionConfigsSupplied_throwsException:102 Expected com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException to be thrown, but nothing was thrown.
[INFO] 
Error:  Tests run: 118, Failures: 1, Errors: 0, Skipped: 0
```

I tried a few different distributions and Java versions, to no avail. Then I tried to see if I could explicitly install Maven 3.9.6 to emulate what had worked for me locally. That led me to this [setup-maven](https://github.com/s4u/setup-maven-action) Github action to use instead of the setup-java action. It allowed me to explicitly setup Maven 3.9.6 with temurin distribution, version 8:
```
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 8
          java-distribution: temurin
          maven-version: 3.9.6

      - name: Clone aws-glue-schema-registry repo
        uses: actions/checkout@v4
        with:
          repository: 'awslabs/aws-glue-schema-registry'
          ref: ${{ (inputs.aws-glue-schema-registry-tag == 'latest') && 'master' || inputs.aws-glue-schema-registry-tag }}
          path: ${{ github.workspace }}/share/aws-glue-schema-registry/

      - name: Build aws-glue-schema-registry tools
        working-directory: ${{ github.workspace }}/share/aws-glue-schema-registry/build-tools/
        # A known error pops up that we can ignore: https://github.com/awslabs/aws-glue-schema-registry/issues/267
        continue-on-error: true
        run: |
          echo $(mvn --version)
          mvn clean install

      # Run in separate step because of known, ignorable error above
      - name: Build aws-glue-schema-registry jars
        working-directory: ${{ github.workspace }}/share/aws-glue-schema-registry/
        run: |
          mvn clean install
          mvn dependency:copy-dependencies
```

Github actions logs confirms the versions I chose. However, I still get the failed test. I tried using 'adopt' distribution instead of 'temurin' with Java version 8 and Maven 3.9.6 but am having the same issue. I guess this is some issue with how we are setting up the Java environment in Github actions (since, again, it works locally), but I'm at a loss as to how we could fix it.

Does this failing test sound familiar and does anyone know of a way to set up the environment, especially in Github actions, correctly?
